CREATE OR REPLACE TABLE CUSTOMER_ORDERS (
    ORDER_ID NUMBER(10,0) NOT NULL,
    CUSTOMER_ID NUMBER(10,0),
    CUSTOMER_NAME VARCHAR(100),
    ORDER_AMOUNT NUMBER(15,2),
    ORDER_DATE TIMESTAMP_NTZ,
    ORDER_STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);