CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(10,0) NOT NULL,
    PRODUCT_NAME VARCHAR(150),
    CATEGORY VARCHAR(50),
    PRICE NUMBER(12,2),
    STOCK_QUANTITY NUMBER(10,0),
    CREATED_DATE DATE,
    IS_AVAILABLE BOOLEAN
);