CREATE OR REPLACE TABLE SALES (
    SALE_ID NUMBER(10,0) NOT NULL,
    PRODUCT_ID NUMBER(10,0),
    CUSTOMER_ID NUMBER(10,0),
    SALE_AMOUNT NUMBER(15,2),
    SALE_DATE TIMESTAMP_NTZ,
    PAYMENT_STATUS VARCHAR(30),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);