!source env_config.sql

CREATE OR REPLACE TABLE IDENTIFIER($env_prefix || '_STIBO.ODS.CUSTOMER') (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(255),
    EMAIL           VARCHAR(255),
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);